### PR TITLE
[alpha] fixes in dependency resolver (issues #302, #308)

### PR DESCRIPTION
**Pull request by henrychi2**
Fixes in dependency resolver for issues #302 and #308

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by ddebrunner** [comment]
This didn't seem to fix #308 

spl-app-info --files *.sab

shows no files from the pip installed module.

**Comment by henrychi2** [comment]
I cannot seem to recreate this.  I posted my full application below.  May I try your application in my environment?  Thanks.
```
$ python3 --version
Python 3.5.1

$ pip3 freeze
oauthlib==1.0.3
requests==2.9.1
requests-oauthlib==0.6.1
TwitterAPI==2.4.1
```

**1) test_twitter.py**
```
from streamsx.topology.topology import Topology
import streamsx.topology.context
import test_twitter_functions

def main():
    topo = Topology("test_twitter")
    source = topo.source(test_twitter_functions.source_tuples)
    source.sink(print)
    streamsx.topology.context.submit("STANDALONE", topo.graph)
     
if __name__ == '__main__':
    main()
```
**2) test_twitter_functions.py**
```
from TwitterAPI import TwitterAPI

def source_tuples():
    return ["Hello", "World!"]
```

**3) Output of spl-app-info shows TwitterAPI**
```
$ spl-app-info --files *.sab
...
Toolkit: tk8853706574979572531  Version: 1.0.0
   opt/python/modules/test_twitter_functions.py
   opt/python/packages/TwitterAPI/__init__.py
   opt/python/packages/TwitterAPI/TwitterError.py
   opt/python/packages/TwitterAPI/__pycache__/__init__.cpython-35.opt-2.pyc
   opt/python/packages/TwitterAPI/__pycache__/TwitterOAuth.cpython-35.opt-1.pyc
   opt/python/packages/TwitterAPI/__pycache__/TwitterError.cpython-35.opt-2.pyc
   opt/python/packages/TwitterAPI/__pycache__/BearerAuth.cpython-35.opt-1.pyc
   opt/python/packages/TwitterAPI/__pycache__/TwitterRestPager.cpython-35.pyc
   opt/python/packages/TwitterAPI/__pycache__/BearerAuth.cpython-35.opt-2.pyc
...
```

**Comment by ddebrunner** [comment]
My app is similar to yours except that I actually use TwitterAPI, here's pip show output:

```
$ pip3 show TwitterAPI
---
Metadata-Version: 1.1
Name: TwitterAPI
Version: 2.4.1
Summary: Minimal wrapper for Twitter's REST and Streaming APIs
Home-page: https://github.com/geduldig/TwitterAPI
Author: Jonas Geduldig
Author-email: boxnumber03@gmail.com
License: MIT
Location: /usr/local/lib/python3.4/site-packages
Requires: requests, requests-oauthlib
```

**Comment by henrychi2** [comment]
I noticed that the location of your site-packages is in a python3.4 directory (e.g. /usr/local/lib/python3.4/site-packages).  When I tried installing Python 3.4, I remember I couldn't submit the application since the method call `subprocess.run()` in context.py is new to Python 3.5, so I switched to using 3.5.

A couple of questions.
1) Are you able to submit the application using Python 3.4?
2) If you are using Python 3.5, do you have any 3.4 directories like site-packages in the `sys.path`?  If so, I think I can make a simple change to support this.  Thanks.
```
>> sys.path
['', '/usr/local/lib/python35.zip', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/usr/local/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages']
```

**Comment by ddebrunner** [comment]
```
[streamsadmin@streamsqse twit]$ python3
Python 3.5.0 (default, Oct 12 2015, 11:39:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> sys.path
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'sys' is not defined
>>> import sys
>>> sys.path
['', '/home/streamsadmin/topology_pr/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages', '/usr/local/lib/python3.4/site-packages', '/usr/local/lib/python35.zip', '/usr/local/lib/python3.5', '/usr/local/lib/python3.5/plat-linux', '/usr/local/lib/python3.5/lib-dynload', '/usr/local/lib/python3.5/site-packages']
>>> 
```

**Comment by henrychi2** [comment]
Thanks for the info.  I've created pull request #319 that might help.

**Pull request merged**
