### PR TITLE
[WIP] Https issue encountered with httpcomponents-client-4.3.6

### PR DESCRIPTION
**Pull request by yvchan**
NOTE:  I do not intend to merge this, it's for reference to help resolve an issue I'm encountering.

sample code in java/src/com/ibm/streamsx/rest/StreamsConnection.java to show the problem i'm encountering.

To repro:  run ant to build the file, and you can run it with the following against a bluemix service:

java -cp $STREAMSX_TOPOLOGY_INSTALL/lib/com.ibm.streamsx.topology.jar $DEBUGGING com.ibm.streamsx.rest.StreamsConnection  $USER $PASSWD $STREAMS_REST_URL instances/$INSTANCE

where $USER, $PASSWD and $INSTANCE are self explanatory, and $STREAMS_REST_URL is the url to access the streams rest api in bluemix.  

This should produce the following output with httpcomponents-client-4.3.6:
'''
Request: https://streams-console-c6d1.ng.bluemix.net/streams/rest/instances/49d495e5-563f-4b5c-8d2a-87d184113a69
Apr 20, 2017 6:34:41 PM org.apache.http.impl.auth.HttpAuthenticator handleAuthChallenge
WARNING: Malformed challenge: Authentication challenge is empty
org.apache.http.client.HttpResponseException: Unauthorized
        at org.apache.http.client.fluent.ContentResponseHandler.handleResponse(ContentResponseHandler.java:47)
        at org.apache.http.client.fluent.ContentResponseHandler.handleResponse(ContentResponseHandler.java:40)
        at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
        at org.apache.http.client.fluent.Response.returnContent(Response.java:97)
        at com.ibm.streamsx.rest.StreamsConnection.getResponseString(StreamsConnection.java:60)
        at com.ibm.streamsx.rest.StreamsConnection.main(StreamsConnection.java:89)
'''

whereas if you set $DEBUGGING to ``` export DEBUGGING="-Dorg.apache.commons.logging.Log=org.apache.commons.logging.impl.SimpleLog -Dorg.apache.commons.logging.simplelog.showdatetime=true -Dorg.apache.commons.logging.simplelog.log.org.apache.http=DEBUG" ```

you'll get the details output that shows the error 

```
2017/04/20 18:58:37:598 EDT [DEBUG] HttpAuthenticator - streams-console-c6d1.ng.bluemix.net:443 requested authentication
2017/04/20 18:58:37:598 EDT [DEBUG] TargetAuthenticationStrategy - Authentication schemes in the order of preference: [negotiate, Kerberos, NTLM, Digest, Basic]
2017/04/20 18:58:37:598 EDT [DEBUG] TargetAuthenticationStrategy - Challenge for negotiate authentication scheme not available
2017/04/20 18:58:37:598 EDT [DEBUG] TargetAuthenticationStrategy - Challenge for Kerberos authentication scheme not available
2017/04/20 18:58:37:598 EDT [DEBUG] TargetAuthenticationStrategy - Challenge for NTLM authentication scheme not available
2017/04/20 18:58:37:598 EDT [DEBUG] TargetAuthenticationStrategy - Challenge for Digest authentication scheme not available
2017/04/20 18:58:37:599 EDT [WARN] HttpAuthenticator - Malformed challenge: Authentication challenge is empty
2017/04/20 18:58:37:603 EDT [DEBUG] ResponseProcessCookies - Cookie accepted [DPJSESSIONID="PBC5YS:-518333900", version:0, domain:.streams-console-c6d1.ng.bluemix.net, path:/, expiry:null]
```

Replacing this with the latest 4.5.3 of httpcomponents-client, and re-building has solved the problem for me, but that version of httpclient is not in streamsx.topology, so if  someone could help explain why this is failing in my sample, but not in the RestUtils of topology/internal, that would be appreciated.

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by ddebrunner** [comment]
Is it possible you can use the same authentication approach as the existing code while using the fluent api?

**Comment by ddebrunner** [comment]
I got this working by using the same authentication header as the existing code uses:
Here's a diff
```
diff --git a/java/src/com/ibm/streamsx/rest/StreamsConnection.java b/java/src/co
index 1eaba86..3c40de5 100644
--- a/java/src/com/ibm/streamsx/rest/StreamsConnection.java
+++ b/java/src/com/ibm/streamsx/rest/StreamsConnection.java
@@ -19,6 +19,11 @@ import org.apache.http.auth.UsernamePasswordCredentials ;
 import org.apache.http.auth.Credentials ;
 import org.apache.http.auth.AuthScope ;
 
+import org.apache.http.auth.AUTH;
+import java.nio.charset.StandardCharsets;
+import javax.xml.bind.DatatypeConverter;
+
+
 public class StreamsConnection {
 
    private Credentials credentials ;
@@ -26,6 +31,8 @@ public class StreamsConnection {
    private AuthCache authCache = new BasicAuthCache() ;
    private String url ;
 
+   private String apiKey;
+
    private Executor executor ;
 
    public StreamsConnection( String userName, String authToken, String url ) 
@@ -34,13 +41,16 @@ public class StreamsConnection {
          URL xUrl = new URL( url ) ;
          String hostName = xUrl.getHost() ;
 
-         this.credentials = new UsernamePasswordCredentials( userName, authToke
+         //this.credentials = new UsernamePasswordCredentials( userName, authTo
          this.httpHost = new HttpHost( hostName ) ;
 
+         String api_creds = userName + ":" + authToken;
+         this.apiKey = "Basic " + DatatypeConverter.printBase64Binary(api_creds
+
          this.authCache.put( httpHost, new BasicScheme() ) ;
  
-         this.executor = Executor.newInstance()
-           .auth( credentials ) ;
+         this.executor = Executor.newInstance();
+//           .auth( credentials ) ;
            
          this.url = url ;
       } catch (MalformedURLException e ) {
@@ -54,6 +64,8 @@ public class StreamsConnection {
       try {
         Request request = Request.Get( inputString )
                           .useExpectContinue() ;
+        
+        request.addHeader(AUTH.WWW_AUTH_RESP, this.apiKey);
         Response response = executor.execute( request ) ;
 
         // TODO: need to decode errors

```

**Comment by yvchan** [comment]
thanks @ddebrunner   I will change the way I am setting up the authentication and close this request.

**Pull request closed without merging**
