### PR TITLE
Adding lowlatency/endlowlatency

### PR DESCRIPTION
**Pull request by sdickes**
[WIP] lowlatency/endlowlatency virtual operators.

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by ddebrunner** [comment]
What's the purpose of regions in the python code?

**Comment by sdickes** [comment]
Good question and I do not know if I have the full answer but when looking through the the java code for lowlatency and parallel operators and at the resultant json ouptut I see a region that gets added that has the name of the virtual operator. 
For example, I see this at line 104 in "java/src/com/ibm/streamsx/topology/builder/GraphBuilder.java"

BOutput lowLatencyOutput = addPassThroughMarker(parent, BVirtualMarker.LOW_LATENCY, true);

and the last argument controls the creation of the region, from what I can see. 

line 188 has this 

        if (createRegion) {
            final String regionName = op.op().getName();
            regionMarkers.put(regionName, virtualMarker.kind());
            op.addRegion(regionName);
        }

**Comment by ddebrunner** [comment]
@wmarshall484 

Any thoughts on if regions are needed at this point?

I would have expected they are added during the processing of the markers, in the existing java code.

**Comment by wmarshall484** [comment]
Regions are not needed in the python code. They are used by the SPL generator to hold information about operations like PE placement. With respect to generating correct parallel/lowLatency/isolate regions from python code, it's only important that the kinds are correctly named, e.g.:
``` Java
public enum BVirtualMarker {
    UNION("$Union$"),
    PARALLEL("$Parallel$"),
    END_PARALLEL("$EndParallel$"),
    LOW_LATENCY("$LowLatency$"),
    END_LOW_LATENCY("$EndLowLatency$"),
    ISOLATE("$Isolate$");
...
}
```

**Pull request merged**
