### PR TITLE
Checkpoint 1698

### PR DESCRIPTION
**Pull request by EricMichaelJohnson**
Enable the user's class to suppress the exception thrown when the user's callable object cannot be dilled.  When this happens, processing continues with no checkpoint support for the operator using the callable that cannot be dilled.

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by EricMichaelJohnson** [comment]
I did some ad-hoc testing to ensure that this works with exceptions suppressed and not suppressed.  I can add automated tests.

**Comment by ddebrunner** [comment]
jenkins run tests

**Comment by ddebrunner** [comment]
Why is the documentation being removed from `checkpoint_period`?

**Comment by EricMichaelJohnson** [comment]
fixes #1698

**Pull request merged**
