### PR TITLE
[WIP] Subcribe support for python receiving rstring SPL type

### PR DESCRIPTION
**Pull request by sdickes**
WIP
subscribe support for python receiving rstring SPL type
rstring is converted to python string, pickled, and sent downstreams

### CODE REVIEW

**Comment by ddebrunner** [comment]
Could you expand more of what the user functionality is?

I wouldn't have expected rstrings to be pickled.

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by sdickes** [comment]
What I added was for python to subscribe to a topic that has type rstring. The input type is rstring so a new C++ operator type is inserted into the graph to: convert the rstring to a Python string; pickle the result; and then submit the new tuple to the output port. This allows the next operator, written in Python, to process this input tuple. 

This is a [WIP] as I am not sure if this is the correct approach but it definitely works. 
A fuller question is what types should Python support and is there a generic approach to support them?

**Comment by ddebrunner** [comment]
My intention (and some fragments of code exist in the operators) that the rstring for the Schema String would be passed directly into the Python code (as a Python string) as the function argument.
No need to create an additional operator to pickle it.

**Comment by sdickes** [comment]
So the fragments are the $attr checks for '__spl_po' or 'string' or 'jsonString' that set $pystyle?

**Comment by ddebrunner** [comment]
yes

**Comment by sdickes** [comment]
Tthis pull request should be closed based on the other pubsub changes, correct?

**Pull request closed without merging**
