### PR TITLE
Update Apache HttpClient jars to version 4.5.2 

### PR DESCRIPTION
**Pull request by johnmac-ibm**
Still testing, but wanted to make available for discussion

### CODE REVIEW

**Comment by pgerv12** [comment]
Tested within my environment and no http-related issues were seen.

**Comment by ddebrunner** [comment]
@pgerv12 So is it ready for merging , so no longer a WIP?

**Comment by pgerv12** [comment]
Yes, I think so. I can't edit anything though

**Comment by ddebrunner** [comment]
I'm going to run tests with this.

**Comment by ddebrunner** [comment]
Tested with a subset of Python tests against the three current types of services - (legacy, vm and container)

**Comment by ddebrunner** [comment]
Passes the Java REST api tests.

**Pull request merged**
