### PR TITLE
Update build.xml to work with Ant 1.9.1 - Issue #207

### PR DESCRIPTION
**Pull request by cancilla**
Fix for issue #207: 

The javadoc task added the "failonwarning" attribute in Ant v1.9.4. However, out current build environment is setup to use Ant 1.9.1. As a result, this toolkit fails to build. Due to technical issues, the environment cannot be upgraded to the latest Ant version at this time.

Therefore, I am requesting that the "failonwarning" attribute be removed from the javadoc task in order to support building the toolkit on Ant v1.9.1.

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by ddebrunner** [comment]
Hmmm, the fail on warning was added so that the javadoc warnings are caught automatically for any pull request, otherwise javadoc warnings may only be discovered later.

**Comment by ddebrunner** [comment]
Btw @cancilla if you rebase your fork you can avoid using pull requests to bring your master in line with  the IBMStreams master. Using rebasing also results in your master being at the same level as the IBMStreams master rather than one empty commit ahead (or is it behind).

See https://github.com/IBMStreams/streamsx.topology/wiki/Useful-Git-GitHub-info

**Comment by dlaboss** [comment]
maybe the doc doc tgt can be conditionalized and omit failonwarning unless its ant 1.9.4 or higher?  if not, maybe add a docNofailonwarning tgt that the Streams build can use.

**Comment by cancilla** [comment]
@dlaboss, thanks for the suggestions. I looked at adding conditions to the doc target but this would likely require using ant-contrib, which would add a dependency to the toolkit. This is probably not what we want. I also looked into adding a new target as you suggested, but this is difficult. The Streams build simply calls the "all" target in this file. So there is not easy to hook into this new doc target.

**Comment by dlaboss** [comment]
@cancilla yeah, it's a pain. A tad gaggy / there may be a better way but this seems to do the trick w/o ant-contrib.  Replace the "doc" task with:
```
  <target name="checkAntVersion">
	<condition property="ant_ge_1_9_4">
        <antversion atleast="1.9.4"/>
	</condition>
    <condition property="ant_lt_1_9_4">
        <not>
            <antversion atleast="1.9.4"/>
        </not>
    </condition>
  </target>

  <property name="topology.doc.windowTitle" value="Java Application API for InfoSphere Streams"/>
  <property name="topology.doc.footer" value="streamsx.topology 0.9 beta @ IBMStreams GitHub"/>

  <target name="doc" depends="checkJava8,checkAntVersion,docFailonwarning,docNoFailonwarning"/>

  <target name="docFailonwarning" if="ant_ge_1_9_4">
       <mkdir dir="${tk}/doc"/>
       <ant dir="samples/java/functional" target="doc"/>
       <mkdir dir="${tk}/doc/samples/javadoc"/>
       <copy todir="${tk}/doc/samples/javadoc">
           <fileset dir="samples/java/functional/javadoc"/>
       </copy>
       <javadoc destdir="${tk}/doc/javadoc" classpathref="javadoc.classpath"
          Overview="java/src/overview.html"
          Windowtitle="${topology.doc.windowTitle}"
          Footer="${topology.doc.footer}"
          failonwarning="yes"
          additionalparam="${disableJavadocLint}"
          >
            <fileset dir="java/src">
               <include name="com/ibm/streamsx/topology/**"/>
               <exclude name="com/ibm/streamsx/topology/internal/**"/>
            </fileset>
       </javadoc>
       <ant dir="toolkit" target="spldoc"/>
  </target>

  <target name="docNoFailonwarning" if="ant_lt_1_9_4">
       <mkdir dir="${tk}/doc"/>
       <ant dir="samples/java/functional" target="doc"/>
       <mkdir dir="${tk}/doc/samples/javadoc"/>
       <copy todir="${tk}/doc/samples/javadoc">
           <fileset dir="samples/java/functional/javadoc"/>
       </copy>
       <javadoc destdir="${tk}/doc/javadoc" classpathref="javadoc.classpath"
          Overview="java/src/overview.html"
          Windowtitle="${topology.doc.windowTitle}"
          Footer="${topology.doc.footer}"
          additionalparam="${disableJavadocLint}"
          >
            <fileset dir="java/src">
               <include name="com/ibm/streamsx/topology/**"/>
               <exclude name="com/ibm/streamsx/topology/internal/**"/>
            </fileset>
       </javadoc>
       <ant dir="toolkit" target="spldoc"/>
  </target>
```

**Comment by ddebrunner** [comment]
Closing this as the 1.9.4 functionality is being used by the project.

**Pull request closed without merging**
