### PR TITLE
Submission results should be interactable.

### PR DESCRIPTION
**Pull request by wmarshall484**
Only WIP because I'm running the python tests locally before indicating that this is ready to be merged.

**Changes.**
* The result of `submit` now returns an instance of the `SubmissionResult` class.
  * The `SubmissionResult` class allows access of fields through `[]` notation or dot notation.
* The `StreamsConnection`, when possible, is returned in the submission result

### CODE REVIEW

**Comment by wmarshall484** [comment]
UPDATE: 
Had to override the `__contains__` method which corresponds to Python's `in` keyword.

Rerunning tests.

**Comment by wmarshall484** [comment]
Update: test2_test.test_local_check referred to `Tester.sc` instead of `Tester.streams_connection`

**Comment by wmarshall484** [comment]
Other than that, there was a non-repeatable failure in `test2_views.TestViews`:
```
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py", line 132, in make_request
    return self.session.get(url).json()
  File "/home/streamsadmin/anaconda3/lib/python3.5/site-packages/requests/models.py", line 826, in json
    return complexjson.loads(self.text, **kwargs)
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/streamsadmin/anaconda3/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

It worked when I re ran the test, so either this was an issue with Bluemix, or we have a timing issue with requesting Streams REST resource elements.

**Comment by wmarshall484** [comment]
Rerunning tests.

**Comment by ddebrunner** [comment]
Yeah, I've seen that issue with test2_views.py.

**Comment by wmarshall484** [comment]
Getting another non repeatable error. I've run the python tests 3 times, and the errors I've encountered don't seem to be related to these changes, but rather unpredictable failures with REST requests.
```
======================================================================
ERROR: test_object_view (test2_views.TestViews)
Test a view of Python objects.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/streamsadmin/git/streamsx.topology/test/python/topology/test2_views.py", line 54, in test_object_view
    tester.test(self.test_ctxtype, self.test_config)
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 247, in test
    passed = self._distributed_test(config, username, password)
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 283, in _distributed_test
    return self._distributed_wait_for_result()
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 301, in _distributed_wait_for_result
    self.result = cc._complete()
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 502, in _complete
    check = self. __check_once()
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 526, in __check_once
    cms = self._get_job_metrics()
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/topology/tester.py", line 580, in _get_job_metrics
    for op in self.job.get_operators():
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py", line 298, in get_operators
    return self._get_elements(self.operators, 'operators', Operator)
  File "/home/streamsadmin/git/streamsx.topology/com.ibm.streamsx.topology/opt/python/packages/streamsx/rest_primitives.py", line 90, in _get_elements
    json_elements = self.rest_client.make_request(url)[key]
KeyError: 'operators'
```

**Comment by wmarshall484** [comment]
I'm running `python -m unittest test2*.py` again, but if I don't see any failures directly related to these changes, I'm tempted to remove the WIP tag and open this up for merging. That might be hasty, though.

@ddebrunner, thoughts?

**Comment by wmarshall484** [comment]
I'm not seeing failures in any test other than test2_views.py, so I'm going to remove the WIP tag.

**Pull request merged**
