### PR TITLE
New Python Wrapper Functions required for Publish and Subscribe issue #2093

### PR DESCRIPTION
**Pull request by joergboe**
This PR is available for discussion.

See #2093

### CODE REVIEW

**Comment by ddebrunner** [comment]
I'm reluctant to increase the surface area of the api to handle special cases. Most likely this can be done with a decorator on the `publish` and `subscribe` operators that effectively implements the last solution (by Aviendha) in this: https://stackoverflow.com/questions/26515595/how-does-one-ignore-unexpected-keyword-arguments-passed-to-a-function

If we do add additional methods then a dictionary comprehension would be a one liner that replaces most of the code from 592 to 607 and 1754 to 1759 , e.g.

```
ca = {k: connection[k] for k in ('topic', 'schema', 'connection_mode', 'buffer_capacity', 'buffer_full_policy') if k in connection}
self.subscribe(**ca)
```

**Comment by ddebrunner** [comment]
I also wonder if instead of having the connection definition use 'Python', 'String' why not just always use the SPL schemas, and let clients decide how to map it into their local representation.

At least `subscribe` and `subscribe_connection` should accept the same values for schema.

**Comment by joergboe** [comment]
I assume that the core module, which generated the connection dictionary is not dependent from all the toolkit modules. Thus I assume all connection values are strings.

**Comment by ddebrunner** [comment]
I mean the string version of the raw SPL schema, e.g. `tuple<rstring string>` rather than `String`, but maybe the logical version is ok, just a pure SPL tool would have to do a conversion.

**Pull request closed without merging**
