### PR TITLE
Fix for GraphUtilities::removeUnionOperator not finding all upstream …

### PR DESCRIPTION
**Pull request by drhvm**
This is the fix required for python Union to work correctly.  I was not able to create a specific test in java for this condition but my unittests seem to run

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by wmarshall484** [comment]
To verify this works, uncomment lines 189 and 190 in com.ibm.streamsx.topology.test.api.IsolateTest, and verify that the test passes. It seems for some reason that this test (which would have caught the error) was not being verified.

**Comment by wmarshall484** [comment]
+1 When com.ibm.streamsx.topology.test.api.IsolateTest#unionIsolateTest passes.

**Comment by drhvm** [comment]
I am having no luck getting that IsolateTest to run with the asserts uncommented, either with my fix or without.  I don't see any other tests with StreamsContext.Type.TOOLKIT that use the assertTrue method call.  Is this valid in the test framework?

**Comment by drhvm** [comment]
I was able to check that the expectedCount which was supposed to be 4 was actually 0.  The json output looks correct.

**Pull request merged**
