### PR TITLE
Translation new language de and translation verification test script 

### PR DESCRIPTION
**Pull request by joergboe**

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by ddebrunner** [comment]
What is the test testing for?

It would be nice if the test was part of the existing testing mechanism, so it was run for an appropriate target.

**Comment by joergboe** [comment]
The test script is made to support the translation verification test. It generates 3 log-messages in all available languages. These messages are presented to the translation team to verify the translation.
So it is currently nor suited for automated test

**Comment by ddebrunner** [comment]
@joergboe Can you add that explanation to the test. Thanks!

**Pull request merged**
