### PR TITLE
Change bundleRoot-->bundlePath

### PR DESCRIPTION
**Pull request by ibmkendrick**
Adds 'bundlePath' to submission result only if keepArtifacts is True.
Fixes IBMStreams/streamsx.topology#775

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by ddebrunner** [comment]
I think this will fail in certain environments as it changed the testing approach in `test1.py` from the old mechanism to the new harness. (by the addition of the setup method).

Also tests should use the assert methods from unittest and not the `assert` statement.

The `test2*` tests use the new "recommended" approach.

**Comment by ddebrunner** [comment]
In the test that doesn't set `keepArtifacts` it should probably test that the `bundlePath` property being there or not matches `keepArtifacts`, as it might be possible in the future to set the keepArtifacts outside of the test (e.g. to resolve issues).

**Comment by ddebrunner** [comment]
Just realized that the bundle path needs to be present in the results even if keep artifacts is False when the topology is submitted to the BUNDLE context. I'm not sure this code will do that.

**Comment by ibmkendrick** [comment]
Latest code changes applied to address the comments above:
1. move original tests to `test2.py` and make use of assert methods from `unittest`
1. In the test case, check for existence of 'bundlePath' base on `keepArtifacts` settings.
1. add BUNDLE context test in `test1.py`
1. 'bundlePath' should be in submission result for BUNDLE context as well. (Even when keepArtifacts is not specified)

**Comment by ddebrunner** [comment]
Thanks for the changes, can I ask for an explicit test of submitting to the bundle context and verifying the path corrected does point to a file that exists.

Can be in its own class in test2.py since it won't be using the topology tester since it does not execute the graph.

**Comment by ibmkendrick** [comment]
Latest code changes applied to address the comments above:
1. Add unit test `TestBundleMethodsNew` class in `test2.py` to test BUNDLE context
1. verifies if the file reference in result['bundlePath'] exists

**Comment by ddebrunner** [comment]
test now

**Pull request merged**
