### PR TITLE
Added the pyStateful parameter to python topology operators.

### PR DESCRIPTION
**Pull request by EricMichaelJohnson**
I added a parameter, pyStateful, to the python topology operators.  It indicates whether on operator has state that needs to be saved when checkpointing.  All source operators are stateful, and other operators are stateful if their callable is not a function.

### CODE REVIEW

**Comment by wmarshall484** [comment]
> operators are stateful if their callable is a function.

Per the `determine_statefullness` method, I think you mean operators are stateful if their callable is not a function.
```
 def _determine_statefulness(self, _callable):
        stateful = not inspect.isroutine(_callable)
        return stateful
```

**Comment by EricMichaelJohnson** [comment]
@wmarshall484, you are correct.  I edited the comment.

**Comment by ddebrunner** [comment]
Why are the parameters optional, when would they not be set?

Why is the mode `AtttributeFree` and not `Constant`?

**Comment by ddebrunner** [comment]
If all source operators are stateful, why does `Source` have an `pyStateful` parameter?

**Comment by EricMichaelJohnson** [comment]
`Source` has a `pyStateful` parameter for two reasons: it prevents source having to be treated as a special case in the operator generation, and it will be easier to change if we find a case in which `Source` should not be stateful.

**Comment by EricMichaelJohnson** [comment]
I tested the simple lambda expression in the filter operator in the filter_echo sample, and it was correctly determined not to be stateful.

**Comment by EricMichaelJohnson** [comment]
I updated the operators to have Constant mode and to be optional.

**Comment by ddebrunner** [comment]
I will merge this once some other fixes have gone into master that are needed for 1.9/1.10.
(this is post 1.10 work).

**Pull request merged**
