### PR TITLE
do not include anaconda pre-loaded packages in SAB

### PR DESCRIPTION
**Pull request by sdickes**
if the running python directory indicates anaconda is being used then exclude from the SAB packages/modules that reside in the anaconda installation tree

### CODE REVIEW

**Comment by ddebrunner** [comment]
Can one of the admins verify this patch?

**Comment by sdickes** [comment]
this code works but is not efficient because it works on on the fully populated list. I will now explore updating the the _DependecyResolver class

**Comment by ddebrunner** [comment]
Can we use system version to see if we are running anancoda, rather than making assumptions about the install location?

http://stackoverflow.com/questions/21282363/any-way-to-tell-if-users-python-environment-is-anaconda

**Comment by ddebrunner** [comment]
Sorry, I wasn't clear, but the requirement is to not add packages that Anaconda installs *by default* into the bundle, not any package that is installed under Anaconda. The issue is that pip install puts packages under anaconda, so a local install might have pip installed package `abc`, but a remote install like Bluemix that only has the out of the box Anaconda would not.

The Anaconda package list is here: https://docs.continuum.io/anaconda/pkg-docs
See the last column for if a package is in the installer.

**Comment by sdickes** [comment]
got it, will make the next change based on the Anaconda package list

**Comment by ddebrunner** [comment]
The list of excluded packages is just that, a list of excluded packages, not a list of conda excluded packages. When running in Anaconda that list is pre-populated by a list of Anaconda pre-installed packages. 

Then can the list be maintained by the topology object, so that an application can add to the list, rather than hidden in the dependency object which is not part of the public api.

**Comment by ddebrunner** [comment]
test now

**Comment by ddebrunner** [comment]
I'm not sure we need a TopologyPackages class, but that can be worked upon as we figure out the api.

I was imaging something simpler, just fields in Topology, so one could do something like:

```
topology.exclude_packages.add('blah')
```

**Comment by sdickes** [comment]
That was my original thought too and the api details will be worked out soon.

**Pull request merged**
